--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: animales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.animales (
    id bigint NOT NULL,
    anio integer NOT NULL,
    extincion boolean NOT NULL,
    nombre character varying(20) NOT NULL,
    tipo character varying(10) NOT NULL,
    CONSTRAINT animales_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ANFIBIO'::character varying, 'AVE'::character varying, 'MAMIFERO'::character varying, 'PEZ'::character varying, 'REPTIL'::character varying])::text[])))
);


ALTER TABLE public.animales OWNER TO postgres;

--
-- Name: animales_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.animales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animales_paises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.animales_paises (
    animal_id bigint NOT NULL,
    pais_id bigint NOT NULL
);


ALTER TABLE public.animales_paises OWNER TO postgres;

--
-- Name: paises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.paises (
    id bigint NOT NULL,
    nombre character varying(20) NOT NULL
);


ALTER TABLE public.paises OWNER TO postgres;

--
-- Name: paises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.paises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animales_paises animales_paises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animales_paises
    ADD CONSTRAINT animales_paises_pkey PRIMARY KEY (animal_id, pais_id);


--
-- Name: animales animales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animales
    ADD CONSTRAINT animales_pkey PRIMARY KEY (id);


--
-- Name: paises paises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paises
    ADD CONSTRAINT paises_pkey PRIMARY KEY (id);


--
-- Name: animales uniqueconstraintanimalnombre; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animales
    ADD CONSTRAINT uniqueconstraintanimalnombre UNIQUE (nombre);


--
-- Name: paises uniqueconstraintpaisnombre; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paises
    ADD CONSTRAINT uniqueconstraintpaisnombre UNIQUE (nombre);


--
-- Name: animales_paises fk_constraint_animales_paises_pais_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animales_paises
    ADD CONSTRAINT fk_constraint_animales_paises_pais_id FOREIGN KEY (pais_id) REFERENCES public.paises(id);


--
-- Name: animales_paises fk_constraint_animales_paises_animal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animales_paises
    ADD CONSTRAINT fk_constraint_animales_paises_animal_id FOREIGN KEY (animal_id) REFERENCES public.animales(id);


--
-- PostgreSQL database dump complete
--

